import usermodel from "../Models/Usermodel.js";
import validator from "validator";
import bcrypt from "bcrypt";
import jwt from "jsonwebtoken";

const createtoken = (id) => {
  return  jwt.sign({ id }, process.env.JWT_SECRET);
};
 
export const UserLogin = async (req, res) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      return res.json({ success: false, msg: "Enter all fields" });
    }

    const user = await usermodel.findOne({ email });
    if (!user) {
      return res.json({ success: false, msg: "User does not exist" });
    }

    const isMatch = await bcrypt.compare(password, user.password);

    if (!isMatch) {
      return res.json({ success: false, msg: "Invalid credentials" });
    }

    const username  = user.name
    const token = createtoken(user._id);
    return res.json({ success: true, token  ,  username  });
  } catch (error) {
    console.log(error);
    return res.json({ success: false, msg: "Failed", error });
  }
};

export const UserRegister = async (req, res) => {
  try {
    const { name, password, email } = req.body;
    const exists = await usermodel.findOne({ email });
    if (exists) {
      res.json({ sucsess: false, msg: "User already Exists" });
    }
    if (!validator.isEmail(email)) {
      return res.json({ success: false, msg: "Plase Enter the Valid Email" });
    }
    if (password.length < 10) {
      return res.json({
        success: false,
        msg: "Enter the strong password which includes more than 10 characters",
      });
    }
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(password, salt);
    const Newuser = new usermodel({
      name,
      email,
      password: hashedPassword,
    });
    const user = await Newuser.save(); ////waha per harr ek login ke liye autogenerated Ids create hongi jo  mongo db me use hi hum register kerenege with bcryipted form
    const token = createtoken(user._id);
    res.json({ success: true, token , name });
    console.log('username is ' + username)
  } catch (error) {
    res.json({ success: false, msg: error.message });
  }
};

export const Admin = async (req, res) => {
 try {
    const {username , password} = req.body;
  if(username && password){
    if(username === process.env.ADMIN_USERNAME && password ===process.env.ADMIN_PASSWORD){
      const token = jwt.sign(username+password , process.env.JWT_SECRET)
      res.json({success:true , token })
    }else{
      res.json({  success:false, message:'Invalid credentiationls'})
    }
  }
 } catch (error) {
  res.json({success:false , message:error.message })
 } 
};


